import React, { useState } from "react";
import { Plan, PlanName, Mentor, Review, FAQ } from "../../types";
import Icon from "../ui/Icon";
import { PLAN_FEATURES } from "../../config/plans";
import AuthModal from "../auth/AuthModal";
import illustration1 from "../../assets/Illustrations/illustration_1.png";
import illustration2 from "../../assets/Illustrations/illustration_2.png";
import illustration3 from "../../assets/Illustrations/illustration_3.png";
import illustration4 from "../../assets/Illustrations/illustration_4.png";
import illustration5 from "../../assets/Illustrations/illustration_5.png";
import { motion } from "framer-motion";

const MOCK_MENTORS: Mentor[] = [
  {
    id: 1,
    name: "John Forex",
    avatar: "https://picsum.photos/seed/mentor1/200",
    experience: 10,
    profitRatio: 85,
    instruments: ["EUR/USD", "GBP/JPY"],
    price: 99,
    roi: 25.5,
    strategy: "Specializing in scalping strategies and market psychology.",
  },
  {
    id: 2,
    name: "Anna Indicators",
    avatar: "https://picsum.photos/seed/mentor2/200",
    experience: 8,
    profitRatio: 92,
    instruments: ["XAU/USD", "US30"],
    price: 149,
    roi: 31.2,
    strategy: "Master of technical analysis and custom indicator development.",
  },
  {
    id: 3,
    name: "Mike Waves",
    avatar: "https://picsum.photos/seed/mentor3/200",
    experience: 12,
    profitRatio: 88,
    instruments: ["BTC/USD", "ETH/USD"],
    price: 129,
    roi: 28.0,
    strategy: "Expert in Elliot Wave theory and cryptocurrency markets.",
  },
];

const MOCK_REVIEWS: Review[] = [
  {
    id: 1,
    name: "Sarah L.",
    avatar: "https://picsum.photos/seed/user1/100",
    text: "The AI signals are incredibly accurate. My portfolio has seen a 20% growth in just three months!",
  },
  {
    id: 2,
    name: "David M.",
    avatar: "https://picsum.photos/seed/user2/100",
    text: "Subscribing to Anna's mentorship was a game-changer. Her insights are worth every penny.",
  },
  {
    id: 3,
    name: "Emily C.",
    avatar: "https://picsum.photos/seed/user3/100",
    text: "A fantastic platform for both new and experienced traders. The tools and community are top-notch.",
  },
];

const MOCK_PLANS: Plan[] = [
  {
    name: PlanName.Free,
    monthlyPrice: 0,
    yearlyPrice: 0,
    features: PLAN_FEATURES.Free,
  },
  {
    name: PlanName.Basic,
    monthlyPrice: 29,
    yearlyPrice: 290,
    features: PLAN_FEATURES.Basic,
  },
  {
    name: PlanName.Pro,
    monthlyPrice: 59,
    yearlyPrice: 590,
    features: PLAN_FEATURES.Pro,
  },
  {
    name: PlanName.Premium,
    monthlyPrice: 99,
    yearlyPrice: 990,
    features: PLAN_FEATURES.Premium,
  },
];

// const MOCK_FAQS: FAQ[] = [
//     { question: "How are the AI signals generated?", answer: "Our signals are generated by a proprietary AI model that analyzes thousands of data points, including technical indicators, market sentiment, and news events, to identify high-probability trading opportunities." },
//     { question: "Can I cancel my subscription anytime?", answer: "Yes, you can cancel your subscription at any time from your billing settings. You will retain access to your plan's features until the end of the current billing cycle." },
//     { question: "How do I become a mentor?", answer: "Experienced traders can apply to become a mentor through their user dashboard. The application process includes a review of your trading history and strategy." },
//     { question: "Is my financial data secure?", answer: "Absolutely. We use industry-standard encryption and security protocols to protect all your data. We never store sensitive payment information on our servers." },
// ];
const Faqs = [
  {
    q: "Can I cancel my subscription anytime?",
    a: "Yes, you can cancel your subscription at any time from your billing settings. You will retain access to your plan's features until the end of the current billing cycle.",
  },
  {
    q: "Is my financial data secure?",
    a: "Absolutely. We use industry-standard encryption and security protocols to protect all your data. We never store sensitive payment information on our servers.",
  },
  {
    q: "Is Trade Companion beginner friendly?",
    a: "Yes. Trade Companion provides easy-to-follow BUY/SELL signals with entry price, stop loss, and take profit levels. Additionally, you can choose from professional mentors who match your trading style and goals.",
  },
  {
    q: "Why is Trade Companion different?",
    a: "Trade Companion simplifies trading by handling the analysis for you. You still place trades yourself, but the platform guides you with signals, risk-adjusted lot sizes, and mentorship support to help you succeed.",
  },
  {
    q: "What more does Trade Companion offer?",
    a: "In addition to signals, Trade Companion provides access to professional forex mentors, risk management recommendations, performance tracking, and learning resources to improve your trading skills.",
  },
  {
    q: "How often will I receive signals?",
    a: "Signal frequency depends on market conditions and your chosen mentor. On average, users receive multiple signals per week, but quality is always prioritized over quantity.",
  },
  {
    q: "Can I use Trade Companion on mobile?",
    a: "Yes. Trade Companion works seamlessly across devices, including mobile, so you can access signals and updates on the go.",
  },
  {
    q: "Does Trade Companion guarantee profits?",
    a: "No trading platform can guarantee profits. Trade Companion increases your chances of success by providing reliable signals, risk-adjusted recommendations, and mentorship—but trading always carries risk.",
  },
  {
    q: "Can I choose my own mentor?",
    a: "Absolutely. Trade Companion allows you to browse and select mentors based on their trading style, ratings, preferred pairs, and pricing.",
  },
  {
    q: "Is my data safe with Trade Companion?",
    a: "Yes. We prioritize your privacy and use industry-standard encryption to ensure your personal data and trading information remain secure.",
  },
];

interface LandingPageProps {
  onLoginRequest: (userDetails: { name: string; email: string }) => void;
}

const LandingPage: React.FC<LandingPageProps> = ({ onLoginRequest }) => {
  const [isYearly, setIsYearly] = useState(false);
  const [openFaq, setOpenFaq] = useState<number | null>(null);
  const [mentorSearchQuery, setMentorSearchQuery] = useState("");

  // Auth Modal State
  const [isAuthModalOpen, setIsAuthModalOpen] = useState(false);
  const [authMode, setAuthMode] = useState<"login" | "signup">("login");

  const cardVariant = {
    hidden: { opacity: 0, y: 40 },
    visible: { opacity: 1, y: 0 },
  };

  const containerVariant = {
    hidden: {},
    visible: {
      transition: {
        staggerChildren: 0.25,
      },
    },
  };

  const blockVariantLeft = {
    hidden: { opacity: 0, x: -90 },
    visible: { opacity: 1, x: 0 },
  };
  const blockVariantRight = {
    hidden: { opacity: 0, x: 90 },
    visible: { opacity: 1, x: 0 },
  };

  const toggleFaq = (index: number) => {
    setOpenFaq(openFaq === index ? null : index);
  };

  const openLogin = () => {
    setAuthMode("login");
    setIsAuthModalOpen(true);
  };

  const openSignup = () => {
    setAuthMode("signup");
    setIsAuthModalOpen(true);
  };

  const filteredMentors = MOCK_MENTORS.filter(
    (mentor) =>
      mentor.name.toLowerCase().includes(mentorSearchQuery.toLowerCase()) ||
      mentor.instruments.some((instrument) =>
        instrument.toLowerCase().includes(mentorSearchQuery.toLowerCase())
      )
  );

  return (
    <div className="bg-light-bg min-h-screen text-dark-text">
      {/* Header */}
      <header className="fixed top-0 left-0 right-0 bg-light-surface/80 backdrop-blur-sm z-50 shadow-sm">
        <div className="container mx-auto px-6 py-4 flex justify-between items-center">
          <h1 className="text-2xl font-bold text-primary">Trade Companion</h1>
          <nav className="hidden md:flex items-center space-x-6">
            <a
              href="#features"
              className="text-mid-text hover:text-primary transition-colors"
            >
              Features
            </a>
            <a
              href="#education"
              className="text-mid-text hover:text-primary transition-colors"
            >
              Education
            </a>
            <a
              href="#mentors"
              className="text-mid-text hover:text-primary transition-colors"
            >
              Mentors
            </a>
            <a
              href="#pricing"
              className="text-mid-text hover:text-primary transition-colors"
            >
              Pricing
            </a>
            <a
              href="#faq"
              className="text-mid-text hover:text-primary transition-colors"
            >
              FAQ
            </a>
          </nav>
          <div className="flex items-center space-x-4">
            <button
              onClick={openLogin}
              className="text-primary hover:text-primary-hover font-semibold transition-colors"
            >
              Login
            </button>
            <button
              onClick={openSignup}
              className="bg-primary hover:bg-primary-hover text-white font-semibold py-2 px-4 rounded-lg transition-colors"
            >
              Get Started
            </button>
          </div>
        </div>
      </header>

      <main>
        {/* Hero Section */}
        <section
          style={{ height: "100vh" }}
          className="pt-32 pb-20 text-center bg-light-hover"
        >
          <div className="container mx-auto px-6 items-center justify-center flex flex-col h-full">
            <h2 className="text-5xl md:text-6xl font-extrabold leading-tight mb-4 text-dark-text">
              Trade Smarter, Not Harder
            </h2>
            <p className="text-xl text-mid-text max-w-3xl mx-auto mb-8">
              Leverage AI-powered signals and expert mentorship to elevate your
              Forex trading performance.
            </p>
            <button
              onClick={openSignup}
              className="bg-primary hover:bg-primary-hover text-white font-bold py-3 px-8 rounded-full text-lg transition-transform transform hover:scale-105"
            >
              Start Your Free Trial
            </button>
          </div>
        </section>

        {/* {Features Section} */}
        <section id="features" className="py-20 bg-light-bg">
          <div className="conatiner flex-col flex gap-8 items-center px-6 mx-auto">
            <motion.div
              variants={blockVariantLeft}
              initial="hidden"
              whileInView="visible"
              viewport={{ once: false, amount: 0.5 }}
              transition={{ duration: 0.6, ease: "easeOut" }}
              className="max-w-6xl w-full h-[400px] grid grid-cols-1 md:grid-cols-2 gap-12 justify-center items-center"
            >
              <div className="flex w-full h-max items-center justify-center">
                <img
                  src={illustration1}
                  alt="Illustration"
                  className="w-[80%] max-w-md mr-4"
                />
              </div>
              <div className="flex gap-4 flex-col text-left items-start justify-center h-full">
                <h1 className="text-4xl font-bold text-center mb-4 text-dark-text text-left">
                  Signal Generation
                </h1>
                <p className="text-mid-text">
                  Get Signals from both our verified professionals and also from
                  our own crafted and well fed Signal generator model.
                </p>
              </div>
            </motion.div>

            <motion.div
              variants={blockVariantRight}
              initial="hidden"
              whileInView="visible"
              viewport={{ once: false, amount: 0.5 }}
              transition={{ duration: 0.6, ease: "easeOut" }}
              className="max-w-6xl w-full h-[400px] grid grid-cols-1 md:grid-cols-2 gap-12 justify-center items-center mt-12"
            >
              <div className="flex gap-4 flex-col items-end justify-center h-full md:order-1 order-2">
                <h1 className="text-4xl font-bold text-center mb-4 text-dark-text text-right">
                  Learn how to use signals from professionals
                </h1>
                <p className="text-mid-text text-right">
                  We don't just give you signals, we teach you how to use and
                  understand them.
                </p>
              </div>
              <div className="flex w-full h-max items-center justify-center md:order-2 order-1">
                <img
                  src={illustration2}
                  alt="Illustration"
                  className="w-[90%] max-w-md mr-4"
                />
              </div>
            </motion.div>

            <motion.div
              variants={blockVariantLeft}
              initial="hidden"
              whileInView="visible"
              viewport={{ once: false, amount: 0.5 }}
              transition={{ duration: 0.6, ease: "easeOut" }}
              className="max-w-6xl w-full h-[400px] grid grid-cols-1 md:grid-cols-2 gap-12 justify-center items-center"
            >
              <div className="flex w-full h-max items-center justify-center">
                <img
                  src={illustration3}
                  alt="Illustration"
                  className="w-[80%] max-w-md mr-4"
                />
              </div>
              <div className="flex gap-4 flex-col text-left items-start justify-center h-full">
                <h1 className="text-4xl font-bold text-center mb-4 text-dark-text text-left">
                  Accurate Signals and Lot Sizes
                </h1>
                <p className="text-mid-text">
                  Our signals and lot sizes are accurate. They are tested and
                  trusted by over 300+ people.
                </p>
              </div>
            </motion.div>

            <motion.div
              variants={blockVariantRight}
              initial="hidden"
              whileInView="visible"
              viewport={{ once: false, amount: 0.5 }}
              transition={{ duration: 0.6, ease: "easeOut" }}
              className="max-w-6xl w-full h-[400px] grid grid-cols-1 md:grid-cols-2 gap-12 justify-center items-center mt-12"
            >
              <div className="flex gap-4 flex-col items-end justify-center h-full md:order-1 order-2">
                <h1 className="text-4xl font-bold text-center mb-4 text-dark-text text-left">
                  You Earn - We Earn
                </h1>
                <p className="text-mid-text text-right">
                  We have your profit in mind, we earn as you earn. You making
                  money from our signals are our top priority.
                </p>
              </div>
              <div className="flex w-full h-max items-center justify-center md:order-2 order-1">
                <img
                  src={illustration4}
                  alt="Illustration"
                  className="w-[90%] max-w-md mr-4"
                />
              </div>
            </motion.div>

            <motion.div
              variants={blockVariantLeft}
              initial="hidden"
              whileInView="visible"
              viewport={{ once: false, amount: 0.5 }}
              transition={{ duration: 0.6, ease: "easeOut" }}
              className="max-w-6xl w-full h-[400px] grid grid-cols-1 md:grid-cols-2 gap-12 justify-center items-center"
            >
              <div className="flex w-full h-max items-center justify-center">
                <img
                  src={illustration5}
                  alt="Illustration"
                  className="w-[80%] max-w-md mr-4"
                />
              </div>
              <div className="flex gap-4 flex-col text-left items-start justify-center h-full">
                <h1 className="text-4xl font-bold text-center mb-4 text-dark-text text-left">
                  Identify Risky Trades
                </h1>
                <p className="text-mid-text">
                  We help you identify risky and loss-full trades with ease and
                  no stress.
                </p>
              </div>
            </motion.div>
          </div>
        </section>

        {/* Education Section */}
        <section id="education" className="py-20 bg-light-hover">
          <div className="container mx-auto px-6">
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6 }}
              viewport={{ once: false }}
              className="text-center mb-16"
            >
              <h3 className="text-4xl font-bold text-dark-text">
                Knowledge is Power
              </h3>
              <p className="text-mid-text mt-4">
                Our education hub is designed to help you grow, no matter your
                experience level.
              </p>
            </motion.div>

            {/* Column Grid + Animations */}
            <motion.div
              variants={containerVariant}
              initial="hidden"
              whileInView="visible"
              viewport={{ once: false }}
              className="grid md:grid-cols-3 gap-8"
            >
              {/* Card 1 */}
              <motion.div
                variants={cardVariant}
                transition={{ duration: 0.6 }}
                className="bg-light-surface p-8 rounded-xl shadow-md border border-light-gray text-center"
              >
                <Icon
                  name="education"
                  className="w-14 h-14 text-primary mx-auto mb-4"
                />
                <h4 className="text-2xl font-semibold text-dark-text">
                  Forex 101
                </h4>
                <p className="text-mid-text mt-2">
                  Master the basics, from pips and lots to market structure.
                </p>
              </motion.div>

              {/* Card 2 */}
              <motion.div
                variants={cardVariant}
                transition={{ duration: 0.6 }}
                className="bg-light-surface p-8 rounded-xl shadow-md border border-light-gray text-center"
              >
                <Icon
                  name="analytics"
                  className="w-14 h-14 text-primary mx-auto mb-4"
                />
                <h4 className="text-2xl font-semibold text-dark-text">
                  Technical Analysis
                </h4>
                <p className="text-mid-text mt-2">
                  Learn to read charts, identify patterns, and use indicators.
                </p>
              </motion.div>

              {/* Card 3 */}
              <motion.div
                variants={cardVariant}
                transition={{ duration: 0.6 }}
                className="bg-light-surface p-8 rounded-xl shadow-md border border-light-gray text-center"
              >
                <Icon
                  name="billing"
                  className="w-14 h-14 text-primary mx-auto mb-4"
                />
                <h4 className="text-2xl font-semibold text-dark-text">
                  Risk Management
                </h4>
                <p className="text-mid-text mt-2">
                  Discover strategies to protect your capital and trade
                  sustainably.
                </p>
              </motion.div>
            </motion.div>
          </div>
        </section>

        {/* Top Mentors Section */}
        <section id="mentors" className="py-20 bg-light-bg">
          <div className="container mx-auto px-6">
            <h3 className="text-4xl font-bold text-center mb-4 text-dark-text">
              Meet Our Top Mentors
            </h3>
            <div className="max-w-xl mx-auto mb-12">
              <input
                type="text"
                placeholder="Search by name or instrument (e.g., John, EUR/USD)..."
                value={mentorSearchQuery}
                onChange={(e) => setMentorSearchQuery(e.target.value)}
                className="w-full px-5 py-3 bg-light-surface border border-light-gray rounded-full focus:ring-2 focus:ring-primary focus:outline-none transition-shadow text-dark-text shadow-sm"
              />
            </div>
            {filteredMentors.length > 0 ? (
              <div className="grid md:grid-cols-3 gap-8">
                {filteredMentors.map((mentor) => (
                  <div
                    key={mentor.id}
                    className="bg-light-surface rounded-lg overflow-hidden text-center p-6 transform hover:-translate-y-2 transition-transform duration-300 shadow-md border border-light-gray"
                  >
                    <img
                      src={mentor.avatar}
                      alt={mentor.name}
                      className="w-32 h-32 rounded-full mx-auto mb-4 border-4 border-primary"
                    />
                    <h4 className="text-xl font-bold text-dark-text">
                      {mentor.name}
                    </h4>
                    <p className="text-primary mb-2">
                      {mentor.experience} Years Experience
                    </p>
                    <div className="flex justify-around text-sm my-4">
                      <span>
                        <strong className="text-success">
                          {mentor.profitRatio}%
                        </strong>{" "}
                        Profit Ratio
                      </span>
                      <span>
                        <strong className="text-primary">
                          ${mentor.price}
                        </strong>
                        /month
                      </span>
                    </div>
                    <p className="text-mid-text text-sm mb-4">
                      Trades: {mentor.instruments.join(", ")}
                    </p>
                    <button
                      onClick={openSignup}
                      className="w-full bg-primary/10 text-primary hover:bg-primary hover:text-white font-semibold py-2 px-4 rounded-lg transition-colors"
                    >
                      View Profile
                    </button>
                  </div>
                ))}
              </div>
            ) : (
              <p className="text-center text-mid-text mt-8">
                No mentors found matching your search.
              </p>
            )}
          </div>
        </section>

        {/* Pricing Section */}
        <section id="pricing" className="py-20 bg-light-hover">
          <div className="container mx-auto px-6 text-center">
            <h3 className="text-4xl font-bold mb-4 text-dark-text">
              Flexible Plans for Everyone
            </h3>
            <p className="text-mid-text mb-8">
              Choose the plan that's right for your trading journey.
            </p>
            <div className="flex justify-center items-center space-x-4 mb-10 text-dark-text">
              <span>Monthly</span>
              <label className="relative inline-flex items-center cursor-pointer">
                <input
                  type="checkbox"
                  checked={isYearly}
                  onChange={() => setIsYearly(!isYearly)}
                  className="sr-only peer"
                />
                <div className="w-14 h-7 bg-light-gray peer-focus:outline-none rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-0.5 after:left-[4px] after:bg-white after:border-light-gray after:border after:rounded-full after:h-6 after:w-6 after:transition-all peer-checked:bg-primary"></div>
              </label>
              <span className="flex items-center">
                Yearly{" "}
                <span className="ml-2 text-xs bg-success text-white font-bold px-2 py-0.5 rounded-full">
                  Save 20%
                </span>
              </span>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8 max-w-7xl mx-auto">
              {MOCK_PLANS.map((plan) => (
                <div
                  key={plan.name}
                  className={`bg-light-surface p-8 rounded-xl shadow-md border-2 flex flex-col ${
                    plan.name === PlanName.Pro
                      ? "border-primary"
                      : "border-light-gray"
                  }`}
                >
                  <h4 className="text-2xl font-bold text-primary">
                    {plan.name}
                  </h4>
                  {plan.monthlyPrice > 0 ? (
                    <p className="text-4xl font-extrabold my-4 text-dark-text">
                      $
                      {isYearly
                        ? Math.round(plan.yearlyPrice / 12)
                        : plan.monthlyPrice}
                      <span className="text-base font-normal text-mid-text">
                        /month
                      </span>
                    </p>
                  ) : (
                    <p className="text-4xl font-extrabold my-4 text-dark-text">
                      Free
                    </p>
                  )}
                  {isYearly && plan.monthlyPrice > 0 && (
                    <p className="text-mid-text text-sm -mt-4 mb-4">
                      Billed as ${plan.yearlyPrice} per year
                    </p>
                  )}

                  <ul className="text-left space-y-3 my-8 flex-grow">
                    {plan.features.map((feature) => (
                      <li key={feature} className="flex items-start">
                        <Icon
                          name="check"
                          className="w-5 h-5 text-success mr-2 flex-shrink-0 mt-1"
                        />
                        <span className="text-dark-text">{feature}</span>
                      </li>
                    ))}
                  </ul>
                  <button
                    onClick={openSignup}
                    className={`w-full font-bold py-3 px-6 rounded-lg transition-colors mt-auto ${
                      plan.name === PlanName.Pro
                        ? "bg-primary text-white hover:bg-primary-hover"
                        : "bg-primary/10 text-primary hover:bg-primary hover:text-white"
                    }`}
                  >
                    {plan.monthlyPrice > 0 ? "Choose Plan" : "Start for Free"}
                  </button>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Reviews Section */}
        <section id="reviews" className="py-20 bg-light-bg">
          <div className="container mx-auto px-6">
            <h3 className="text-4xl font-bold text-center mb-12 text-dark-text">
              What Our Users Say
            </h3>
            <div className="grid md:grid-cols-3 gap-8">
              {MOCK_REVIEWS.map((review) => (
                <div
                  key={review.id}
                  className="bg-light-surface p-6 rounded-lg shadow-md border border-light-gray"
                >
                  <div className="flex items-center mb-4">
                    <img
                      src={review.avatar}
                      alt={review.name}
                      className="w-12 h-12 rounded-full mr-4"
                    />
                    <div>
                      <p className="font-semibold text-dark-text">
                        {review.name}
                      </p>
                      <div className="flex text-warning">
                        {[...Array(5)].map((_, i) => (
                          <Icon
                            key={i}
                            name="star"
                            className="w-4 h-4 fill-current"
                          />
                        ))}
                      </div>
                    </div>
                  </div>
                  <p className="text-mid-text">"{review.text}"</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* FAQ Section */}
        <section id="faq" className="py-20 bg-light-hover">
          <div className="container mx-auto px-6 max-w-3xl">
            <h3 className="text-4xl font-bold text-center mb-12 text-dark-text">
              Frequently Asked Questions
            </h3>
            <div className="space-y-4">
              {Faqs.map((faq, index) => (
                <div
                  key={index}
                  className="bg-light-surface rounded-lg shadow-md border border-light-gray"
                >
                  <button
                    onClick={() => toggleFaq(index)}
                    className="w-full flex justify-between items-center text-left p-5 font-semibold text-dark-text"
                  >
                    <span>{faq.q}</span>
                    <Icon
                      name="chevronDown"
                      className={`w-6 h-6 transform transition-transform ${
                        openFaq === index ? "rotate-180" : ""
                      }`}
                    />
                  </button>
                  {openFaq === index && (
                    <div className="px-5 pb-5 text-mid-text">
                      <p>{faq.a}</p>
                    </div>
                  )}
                </div>
              ))}
            </div>
          </div>
        </section>
      </main>

      {/* Footer */}
      <footer className="bg-light-surface border-t border-light-gray py-8">
        <div className="container mx-auto px-6 text-center text-mid-text">
          <p>
            &copy; {new Date().getFullYear()} Trade Companion. All Rights
            Reserved.
          </p>
          <p className="text-sm mt-2">
            Trading Forex involves significant risk. This is not financial
            advice.
          </p>
        </div>
      </footer>
    </div>
  );
};

export default LandingPage;
