import React, { useState } from 'react';
import { Plan, PlanName, Mentor, Review, FAQ } from '../../types';
import Icon from '../ui/Icon';

// FIX: Replaced `bio` with `strategy` and added the required `roi` property to match the Mentor type.
const MOCK_MENTORS: Mentor[] = [
    { id: 1, name: 'John Forex', avatar: 'https://picsum.photos/seed/mentor1/200', experience: 10, profitRatio: 85, instruments: ['EUR/USD', 'GBP/JPY'], price: 99, roi: 25.5, strategy: 'Specializing in scalping strategies and market psychology.' },
    { id: 2, name: 'Anna Indicators', avatar: 'https://picsum.photos/seed/mentor2/200', experience: 8, profitRatio: 92, instruments: ['XAU/USD', 'US30'], price: 149, roi: 31.2, strategy: 'Master of technical analysis and custom indicator development.' },
    { id: 3, name: 'Mike Waves', avatar: 'https://picsum.photos/seed/mentor3/200', experience: 12, profitRatio: 88, instruments: ['BTC/USD', 'ETH/USD'], price: 129, roi: 28.0, strategy: 'Expert in Elliot Wave theory and cryptocurrency markets.' },
];

const MOCK_REVIEWS: Review[] = [
    { id: 1, name: 'Sarah L.', avatar: 'https://picsum.photos/seed/user1/100', text: "The AI signals are incredibly accurate. My portfolio has seen a 20% growth in just three months!" },
    { id: 2, name: 'David M.', avatar: 'https://picsum.photos/seed/user2/100', text: "Subscribing to Anna's mentorship was a game-changer. Her insights are worth every penny." },
    { id: 3, name: 'Emily C.', avatar: 'https://picsum.photos/seed/user3/100', text: "A fantastic platform for both new and experienced traders. The tools and community are top-notch." },
];

const MOCK_PLANS: Plan[] = [
    { name: PlanName.Basic, monthlyPrice: 29, yearlyPrice: 290, features: ['5 AI Signals per week', 'Telegram Notifications', 'Basic Analytics', 'Community Access'] },
    { name: PlanName.Pro, monthlyPrice: 59, yearlyPrice: 590, features: ['Unlimited AI Signals', 'Advanced Analytics', '1 Mentor Subscription Included', 'Priority Support'] },
    { name: PlanName.Premium, monthlyPrice: 99, yearlyPrice: 990, features: ['All Pro Features', 'Weekly Market Breakdown', 'Direct Access to Top Mentors', 'Personalized Strategy Session'] },
];

const MOCK_FAQS: FAQ[] = [
    { question: "How are the AI signals generated?", answer: "Our signals are generated by a proprietary AI model that analyzes thousands of data points, including technical indicators, market sentiment, and news events, to identify high-probability trading opportunities." },
    { question: "Can I cancel my subscription anytime?", answer: "Yes, you can cancel your subscription at any time from your billing settings. You will retain access to your plan's features until the end of the current billing cycle." },
    { question: "How do I become a mentor?", answer: "Experienced traders can apply to become a mentor through their user dashboard. The application process includes a review of your trading history and strategy." },
    { question: "Is my financial data secure?", answer: "Absolutely. We use industry-standard encryption and security protocols to protect all your data. We never store sensitive payment information on our servers." },
];


interface LandingPageProps {
  onLogin: () => void;
}

const LandingPage: React.FC<LandingPageProps> = ({ onLogin }) => {
  const [isYearly, setIsYearly] = useState(false);
  const [openFaq, setOpenFaq] = useState<number | null>(null);

  const toggleFaq = (index: number) => {
    setOpenFaq(openFaq === index ? null : index);
  };

  return (
    <div className="bg-background min-h-screen text-on-surface">
      {/* Header */}
      <header className="fixed top-0 left-0 right-0 bg-background/80 backdrop-blur-sm z-50">
        <div className="container mx-auto px-6 py-4 flex justify-between items-center">
          <h1 className="text-2xl font-bold text-primary">Trade Companion</h1>
          <nav className="hidden md:flex items-center space-x-6">
            <a href="#features" className="hover:text-primary transition-colors">Features</a>
            <a href="#education" className="hover:text-primary transition-colors">Education</a>
            <a href="#mentors" className="hover:text-primary transition-colors">Mentors</a>
            <a href="#pricing" className="hover:text-primary transition-colors">Pricing</a>
            <a href="#faq" className="hover:text-primary transition-colors">FAQ</a>
          </nav>
          <div className="flex items-center space-x-4">
            <button onClick={onLogin} className="text-on-surface hover:text-primary transition-colors">Login</button>
            <button onClick={onLogin} className="bg-primary hover:bg-primary-hover text-white font-semibold py-2 px-4 rounded-lg transition-colors">
              Get Started
            </button>
          </div>
        </div>
      </header>

      <main>
        {/* Hero Section */}
        <section className="pt-32 pb-20 text-center bg-gray-900">
          <div className="container mx-auto px-6">
            <h2 className="text-5xl md:text-6xl font-extrabold leading-tight mb-4">Trade Smarter, Not Harder</h2>
            <p className="text-xl text-gray-400 max-w-3xl mx-auto mb-8">Leverage AI-powered signals and expert mentorship to elevate your Forex trading performance.</p>
            <button onClick={onLogin} className="bg-primary hover:bg-primary-hover text-white font-bold py-3 px-8 rounded-full text-lg transition-transform transform hover:scale-105">
              Start Your Free Trial
            </button>
          </div>
        </section>

        {/* Features Section */}
        <section id="features" className="py-20">
          <div className="container mx-auto px-6 text-center">
            <h3 className="text-4xl font-bold mb-2">Why Choose Us?</h3>
            <p className="text-gray-400 mb-12">The ultimate toolkit for the modern Forex trader.</p>
            <div className="grid md:grid-cols-3 gap-8">
              <div className="bg-surface p-8 rounded-xl shadow-lg">
                <Icon name="signals" className="w-12 h-12 text-primary mx-auto mb-4"/>
                <h4 className="text-2xl font-semibold mb-2">Custom AI Signals</h4>
                <p className="text-gray-400">High-accuracy signals, tailored to your risk profile, delivered in real-time.</p>
              </div>
              <div className="bg-surface p-8 rounded-xl shadow-lg">
                <Icon name="mentors" className="w-12 h-12 text-primary mx-auto mb-4"/>
                <h4 className="text-2xl font-semibold mb-2">Expert Mentors</h4>
                <p className="text-gray-400">Learn from profitable traders and subscribe to their strategies.</p>
              </div>
              <div className="bg-surface p-8 rounded-xl shadow-lg">
                <Icon name="education" className="w-12 h-12 text-primary mx-auto mb-4"/>
                <h4 className="text-2xl font-semibold mb-2">Education Hub</h4>
                <p className="text-gray-400">Access exclusive articles and guides to sharpen your trading skills.</p>
              </div>
            </div>
          </div>
        </section>

        {/* Education Section */}
        <section id="education" className="py-20 bg-gray-900">
            <div className="container mx-auto px-6 text-center">
                <h3 className="text-4xl font-bold mb-2">Knowledge is Power</h3>
                <p className="text-gray-400 mb-12">Our education hub is designed to help you grow, no matter your experience level.</p>
                <div className="grid md:grid-cols-3 gap-8">
                    <div className="bg-surface p-8 rounded-xl shadow-lg text-center">
                        <Icon name="education" className="w-12 h-12 text-primary mx-auto mb-4"/>
                        <h4 className="text-2xl font-semibold mb-2">Forex 101</h4>
                        <p className="text-gray-400">Master the basics, from pips and lots to market structure.</p>
                    </div>
                    <div className="bg-surface p-8 rounded-xl shadow-lg text-center">
                        <Icon name="analytics" className="w-12 h-12 text-primary mx-auto mb-4"/>
                        <h4 className="text-2xl font-semibold mb-2">Technical Analysis</h4>
                        <p className="text-gray-400">Learn to read charts, identify patterns, and use indicators.</p>
                    </div>
                    <div className="bg-surface p-8 rounded-xl shadow-lg text-center">
                        <Icon name="billing" className="w-12 h-12 text-primary mx-auto mb-4"/>
                        <h4 className="text-2xl font-semibold mb-2">Risk Management</h4>
                        <p className="text-gray-400">Discover strategies to protect your capital and trade sustainably.</p>
                    </div>
                </div>
            </div>
        </section>


        {/* Top Mentors Section */}
        <section id="mentors" className="py-20">
          <div className="container mx-auto px-6">
            <h3 className="text-4xl font-bold text-center mb-12">Meet Our Top Mentors</h3>
            <div className="grid md:grid-cols-3 gap-8">
              {MOCK_MENTORS.map(mentor => (
                <div key={mentor.id} className="bg-surface rounded-lg overflow-hidden text-center p-6 transform hover:-translate-y-2 transition-transform duration-300">
                  <img src={mentor.avatar} alt={mentor.name} className="w-32 h-32 rounded-full mx-auto mb-4 border-4 border-primary" />
                  <h4 className="text-xl font-bold">{mentor.name}</h4>
                  <p className="text-primary mb-2">{mentor.experience} Years Experience</p>
                  <div className="flex justify-around text-sm my-4">
                    <span><strong className="text-green-400">{mentor.profitRatio}%</strong> Profit Ratio</span>
                    <span><strong className="text-blue-400">${mentor.price}</strong>/month</span>
                  </div>
                  <p className="text-gray-400 text-sm mb-4">Trades: {mentor.instruments.join(', ')}</p>
                  <button className="w-full bg-primary/20 text-primary hover:bg-primary hover:text-white font-semibold py-2 px-4 rounded-lg transition-colors">
                    View Profile
                  </button>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Pricing Section */}
        <section id="pricing" className="py-20 bg-gray-900">
          <div className="container mx-auto px-6 text-center">
            <h3 className="text-4xl font-bold mb-4">Flexible Plans for Everyone</h3>
            <p className="text-gray-400 mb-8">Choose the plan that's right for your trading journey.</p>
            <div className="flex justify-center items-center space-x-4 mb-10">
              <span>Monthly</span>
              <label className="relative inline-flex items-center cursor-pointer">
                <input type="checkbox" checked={isYearly} onChange={() => setIsYearly(!isYearly)} className="sr-only peer" />
                <div className="w-14 h-7 bg-gray-700 peer-focus:outline-none rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-0.5 after:left-[4px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-6 after:w-6 after:transition-all peer-checked:bg-primary"></div>
              </label>
              <span className="flex items-center">
                Yearly <span className="ml-2 text-xs bg-green-500 text-white font-bold px-2 py-0.5 rounded-full">Save 20%</span>
              </span>
            </div>
            <div className="grid md:grid-cols-3 gap-8 max-w-5xl mx-auto">
              {MOCK_PLANS.map(plan => (
                <div key={plan.name} className={`bg-surface p-8 rounded-xl shadow-lg border-2 ${plan.name === PlanName.Pro ? 'border-primary' : 'border-transparent'}`}>
                  <h4 className="text-2xl font-bold text-primary">{plan.name}</h4>
                  <p className="text-4xl font-extrabold my-4">
                    ${isYearly ? plan.yearlyPrice / 12 : plan.monthlyPrice}
                    <span className="text-base font-normal text-gray-400">/month</span>
                  </p>
                  {isYearly && <p className="text-gray-400 text-sm -mt-4 mb-4">Billed as ${plan.yearlyPrice} per year</p>}
                  <ul className="text-left space-y-3 my-8">
                    {plan.features.map(feature => (
                      <li key={feature} className="flex items-start">
                        <Icon name="check" className="w-5 h-5 text-green-500 mr-2 flex-shrink-0 mt-1" />
                        <span>{feature}</span>
                      </li>
                    ))}
                  </ul>
                  <button className={`w-full font-bold py-3 px-6 rounded-lg transition-colors ${plan.name === PlanName.Pro ? 'bg-primary text-white hover:bg-primary-hover' : 'bg-primary/20 text-primary hover:bg-primary hover:text-white'}`}>
                    Choose Plan
                  </button>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Reviews Section */}
        <section id="reviews" className="py-20">
          <div className="container mx-auto px-6">
            <h3 className="text-4xl font-bold text-center mb-12">What Our Users Say</h3>
            <div className="grid md:grid-cols-3 gap-8">
              {MOCK_REVIEWS.map(review => (
                <div key={review.id} className="bg-surface p-6 rounded-lg">
                  <div className="flex items-center mb-4">
                    <img src={review.avatar} alt={review.name} className="w-12 h-12 rounded-full mr-4" />
                    <div>
                      <p className="font-semibold">{review.name}</p>
                      <div className="flex text-yellow-400">
                        {[...Array(5)].map((_, i) => <Icon key={i} name="star" className="w-4 h-4 fill-current" />)}
                      </div>
                    </div>
                  </div>
                  <p className="text-gray-400">"{review.text}"</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* FAQ Section */}
        <section id="faq" className="py-20 bg-gray-900">
          <div className="container mx-auto px-6 max-w-3xl">
            <h3 className="text-4xl font-bold text-center mb-12">Frequently Asked Questions</h3>
            <div className="space-y-4">
              {MOCK_FAQS.map((faq, index) => (
                <div key={index} className="bg-surface rounded-lg">
                  <button onClick={() => toggleFaq(index)} className="w-full flex justify-between items-center text-left p-5 font-semibold">
                    <span>{faq.question}</span>
                    <Icon name="chevronDown" className={`w-6 h-6 transform transition-transform ${openFaq === index ? 'rotate-180' : ''}`} />
                  </button>
                  {openFaq === index && (
                    <div className="px-5 pb-5 text-gray-400">
                      <p>{faq.answer}</p>
                    </div>
                  )}
                </div>
              ))}
            </div>
          </div>
        </section>
      </main>

      {/* Footer */}
      <footer className="bg-surface border-t border-gray-800 py-8">
        <div className="container mx-auto px-6 text-center text-gray-400">
          <p>&copy; {new Date().getFullYear()} Trade Companion. All Rights Reserved.</p>
          <p className="text-sm mt-2">Trading Forex involves significant risk. This is not financial advice.</p>
        </div>
      </footer>
    </div>
  );
};

export default LandingPage;