import { PLAN_FEATURES } from "@/config/plans";
import { PlanName } from "@/types";

export const MOCK_MENTORS = [
    { id: 1, name: 'John Forex', avatar: 'https://picsum.photos/seed/mentor1/200', experience: 10, profitRatio: 85, instruments: ['EUR/USD', 'GBP/JPY'], price: 99, roi: 25.5, strategy: 'Specializing in scalping strategies and market psychology.' },
    { id: 2, name: 'Anna Indicators', avatar: 'https://picsum.photos/seed/mentor2/200', experience: 8, profitRatio: 92, instruments: ['XAU/USD', 'US30'], price: 149, roi: 31.2, strategy: 'Master of technical analysis and custom indicator development.' },
    { id: 3, name: 'Mike Waves', avatar: 'https://picsum.photos/seed/mentor3/200', experience: 12, profitRatio: 88, instruments: ['BTC/USD', 'ETH/USD'], price: 129, roi: 28.0, strategy: 'Expert in Elliot Wave theory and cryptocurrency markets.' },
];

export const MOCK_REVIEWS = [
    { id: 1, name: 'Sarah L.', avatar: 'https://picsum.photos/seed/user1/100', text: "The AI signals are incredibly accurate. My portfolio has seen a 20% growth in just three months!" },
    { id: 2, name: 'David M.', avatar: 'https://picsum.photos/seed/user2/100', text: "Subscribing to Anna's mentorship was a game-changer. Her insights are worth every penny." },
    { id: 3, name: 'Emily C.', avatar: 'https://picsum.photos/seed/user3/100', text: "A fantastic platform for both new and experienced traders. The tools and community are top-notch." },
];

export const MOCK_PLANS = [
    { name: PlanName.Free, monthlyPrice: 0, yearlyPrice: 0, features: PLAN_FEATURES.Free },
    { name: PlanName.Basic, monthlyPrice: 29, yearlyPrice: 290, features: PLAN_FEATURES.Basic },
    { name: PlanName.Pro, monthlyPrice: 59, yearlyPrice: 590, features: PLAN_FEATURES.Pro },
    { name: PlanName.Premium, monthlyPrice: 99, yearlyPrice: 990, features: PLAN_FEATURES.Premium },
];

export const MOCK_FAQS = [
    { question: "How are the AI signals generated?", answer: "Our signals are generated by a proprietary AI model that analyzes thousands of data points, including technical indicators, market sentiment, and news events, to identify high-probability trading opportunities." },
    { question: "Can I cancel my subscription anytime?", answer: "Yes, you can cancel your subscription at any time from your billing settings. You will retain access to your plan's features until the end of the current billing cycle." },
    { question: "How do I become a mentor?", answer: "Experienced traders can apply to become a mentor through their user dashboard. The application process includes a review of your trading history and strategy." },
    { question: "Is my financial data secure?", answer: "Absolutely. We use industry-standard encryption and security protocols to protect all your data. We never store sensitive payment information on our servers." },
];

export const TICKER_SYMBOLS = ['EUR/USD', 'GBP/JPY', 'XAU/USD', 'BTC/USD', 'ETH/USD', 'USD/JPY', 'US500'];

export const INITIAL_TICKER = [
    { pair: "EUR/USD", price: "Loading...", change: "..." },
    { pair: "GBP/JPY", price: "Loading...", change: "..." },
    { pair: "XAU/USD", price: "Loading...", change: "..." },
    { pair: "BTC/USD", price: "Loading...", change: "..." },
    { pair: "US500", price: "Loading...", change: "..." },
];

export const ROBOT_SOLILOQUY = [
    "I scan 20+ markets 24/7 so you don't have to!",
    "I analyze charts instantly to find high-probability setups.",
    "Not sure about risk? I'll recommend the exact lot size for your balance.",
    "Busy? I can automate your trades directly to cTrader.",
    "I verify expert mentors so you can follow them with confidence.",
    "I track high-impact news to keep your capital safe.",
    "Have a question? Chat with me anytime for instant analysis!"
];

export const Faqs = [
  {
    q: "Can I cancel my subscription anytime?",
    a: "Yes, you can cancel your subscription at any time from your billing settings. You will retain access to your plan's features until the end of the current billing cycle.",
  },
  {
    q: "Is my financial data secure?",
    a: "Absolutely. We use industry-standard encryption and security protocols to protect all your data. We never store sensitive payment information on our servers.",
  },
  {
    q: "Is Trade Companion beginner friendly?",
    a: "Yes. Trade Companion provides easy-to-follow BUY/SELL signals with entry price, stop loss, and take profit levels. Additionally, you can choose from professional mentors who match your trading style and goals.",
  },
  {
    q: "Why is Trade Companion different?",
    a: "Trade Companion simplifies trading by handling the analysis for you. You still place trades yourself, but the platform guides you with signals, risk-adjusted lot sizes, and mentorship support to help you succeed.",
  },
  {
    q: "What more does Trade Companion offer?",
    a: "In addition to signals, Trade Companion provides access to professional forex mentors, risk management recommendations, performance tracking, and learning resources to improve your trading skills.",
  },
  {
    q: "How often will I receive signals?",
    a: "Signal frequency depends on market conditions and your chosen mentor. On average, users receive multiple signals per week, but quality is always prioritized over quantity.",
  },
  {
    q: "Can I use Trade Companion on mobile?",
    a: "Yes. Trade Companion works seamlessly across devices, including mobile, so you can access signals and updates on the go.",
  },
  {
    q: "Does Trade Companion guarantee profits?",
    a: "No trading platform can guarantee profits. Trade Companion increases your chances of success by providing reliable signals, risk-adjusted recommendations, and mentorship—but trading always carries risk.",
  },
  {
    q: "Can I choose my own mentor?",
    a: "Absolutely. Trade Companion allows you to browse and select mentors based on their trading style, ratings, preferred pairs, and pricing.",
  },
  {
    q: "Is my data safe with Trade Companion?",
    a: "Yes. We prioritize your privacy and use industry-standard encryption to ensure your personal data and trading information remain secure.",
  },
];